### ISSUE TITLE
I would love to be able to point to a public key (like with the private key) rather than having to add it via a cli flag

### ISSUE THREAD

**Issue by dwallraff** [enaml-ops/omg-cli#2]
> --azure-ssh-pub-key "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCg8P/xwjtXp1E+Nkri0GMBZGuRHo7anFDiogfpO6UymCa1nzyPIEomshav7pw/Xr5MqpTPBXTrDA1uC/ohjnmRWCJbDvyWIczjdQGLVWnndZ+Ev4rjxDJOx3FwngQ3ti2XeSD0pB47C4guu7oD+ufsrBFWAfDjylK/8HeYelqTPjVxeikimZ7W27TTJmxT9oftqgRfO3TkBPFB/cMwkRAEOGf/yHfH6oSdDIisCjyw1QgGYGazL97TR77oCTcss0fKarb4hCEX7riQzeI34hxX88wToAmijZYS4exHgqjUeTFmqc95zB9txVmMceWOj0P2tFOsTucJuhVGM2E/xVy5 vcap@local"

That's just annoying...

**Comment by xchapter7x** [comment]
fix to this is in the latest release
https://github.com/enaml-ops/omg-cli/releases/tag/v0.0.9
