### ISSUE TITLE
omg-cli should look in $HOME for its plugins

### ISSUE THREAD

**Issue by ghost** [enaml-ops/omg-cli#21]
omg cli looks in its CWD rather than $HOME for its plugin state.

**Comment by xchapter7x** [comment]
you can now set the plugin base path via an env var. existing behavior and defaults remain the same

ex.
one can now simply set the OMG_PLUGIN_DIR env var to change the plugin dir to wherever they like
ex.
$ OMG_PLUGIN_DIR=~/ ./omg list-products

https://github.com/enaml-ops/omg-cli/commit/45bd22ba800ed09c67552291e82c4121eb24b330
