### ISSUE TITLE
omg-cli for vsphere should not require resource pools

### ISSUE THREAD

**Issue by forddonald** [enaml-ops/omg-cli#26]
when using omg-cli to deploy a bosh director it should not require me to enter a resource pool, as i might not have one.

**Comment by skibum55** [comment]
Looks to me like every cluster has a default resource pool named "Resources".  Can we just make that the default somewhere around [here](https://github.com/enaml-ops/omg-cli/blob/master/plugins/products/bosh-init/vsphere.go#L45)

**Comment by forddonald** [comment]
Not in the UI, maybe via the API. By default, a new cluster has no resource pools as that is dependent on the cluster feature "DRS" being enabled, which it is not by default.

**Comment by xchapter7x** [comment]
removing resource-pool as a required flag. it is not required or expected that a vsphere will have resource-pools.

https://github.com/enaml-ops/omg-cli/commit/54ba6e84776b58628f2f0c409ddb4ee05ab85d81
