### ISSUE TITLE
getting lots of EOF when trying to build a cloud-config - AWS flags don't appear to be working properly

### ISSUE THREAD

**Issue by haydonryan** [enaml-ops/omg-cli#44]
[log.txt](https://github.com/enaml-ops/omg-cli/files/628557/log.txt)

After talking to @zmb3 he recommended a story for this.

**Comment by zmb3** [comment]
Resolved with:
 - 9458b477dc2120c815c5be567e1f2a5854f8a1e3 
 - 5ab89c0b6e21e063d3a76d3922a8f4a013124df6 
 - c418572c448f960379f6b81ec827324318fe3336
