### ISSUE TITLE
String slice arguments are not parsed corectly

### ISSUE THREAD

**Issue by s-matyukevich** [enaml-ops/omg-cli#49]
I try to execute the following command
```
omg-cli photon \
  --dns 10.148.20.5,10.148.20.6
```

on the deployed vm I see in `/etc/resolv.conf`

```
nameserver 10.148.20.5,10.148.20.6
```

Passing coma separated list of values also don't work for '--network-dns-1' flag when deploying cloud-config, though help message says that this parameter expects comma separated list.

**Comment by zmb3** [comment]
Slice flags should be specified by duplicating the flag name.  For example:

`--dns 10.148.20.5 --dns 10.158.20.6`

The exception to this is when the flags are stored in Vault.  In this case, we store a comma separated string in Vault and handle the splitting internally.

You're correct that the help message incorrectly mentions a comma separated list.  We'll fix that.
