### ISSUE TITLE
director_uuid not included when printing manifest

### ISSUE THREAD

**Issue by dwallraff** [enaml-ops/omg-cli#5]
`--print-manifest` doesn't include the `director_uuid` in the manifest it outputs.
If the flags for connecting to bosh-director are supplied, this should be included in the resulting manifest.

**Comment by xchapter7x** [comment]
this is now fixed
https://github.com/enaml-ops/omg-cli/commit/4674a1b15aab429460ef19be538f83608b0a00a9

https://github.com/enaml-ops/omg-cli/releases/tag/v0.0.9
