### ISSUE TITLE
--cpi-name should be removed / defaulted / explained

### ISSUE THREAD

**Issue by haydonryan** [enaml-ops/omg-cli#7]
Trying to do an Azure deployment using OMG of bosh-init deployed microbosh.  

The end user doesn't know what this needs to be set to (default: cpi). 
omg azure --help shows nothing.

Deploying prints this:
Sorry you need to provide [cpi-name] flags to continue

**Comment by calebwashburn** [comment]
Fixed with release - v0.0.10
